import { zip, unzip } from 'fflate';
import { buildPDFBytes } from './pdfExport.js';

function safeName(ch) {
  return (ch.sheet?.identity?.name || 'mage_character').replace(/[^a-z0-9_\- ]/gi, '_');
}

// ── Export ─────────────────────────────────────────────────────────────────

// Builds a ZIP containing one PDF per character and triggers a browser download.
export async function exportAllAsPDFZip(chars) {
  const entries = Object.values(chars);
  if (!entries.length) throw new Error('No characters to export.');

  const files = {};
  const usedNames = {};
  for (const ch of entries) {
    const base  = safeName(ch);
    const count = usedNames[base] = (usedNames[base] || 0) + 1;
    const key   = count > 1 ? `${base}_${count}.pdf` : `${base}.pdf`;
    files[key]  = buildPDFBytes(ch);
  }

  const zipBytes = await new Promise((resolve, reject) => {
    zip(files, { level: 6 }, (err, data) => (err ? reject(err) : resolve(data)));
  });

  const ts       = new Date().toISOString().slice(0, 10);
  const filename = `mage_backup_${ts}.zip`;
  const blob     = new Blob([zipBytes], { type: 'application/zip' });

  // Try native Capacitor path
  try {
    const { Capacitor } = await import('@capacitor/core');
    if (Capacitor?.isNativePlatform?.()) {
      const { getNativeDir } = await import('./backupLocation.js');
      const dirId = getNativeDir();
      const { Filesystem, Directory } = await import('@capacitor/filesystem');
      const dir  = Directory[dirId] || Directory.Documents;
      const path = dirId === 'ExternalStorage' ? `MageBackups/${filename}` : filename;
      if (dirId === 'ExternalStorage') {
        try { await Filesystem.mkdir({ path: 'MageBackups', directory: dir, recursive: true }); } catch {}
      }
      const ab     = await blob.arrayBuffer();
      const bytes  = new Uint8Array(ab);
      let bin = '';
      bytes.forEach(b => { bin += String.fromCharCode(b); });
      await Filesystem.writeFile({ path, data: btoa(bin), directory: dir });
      return;
    }
  } catch { /* fall through */ }

  // Try the user's chosen folder (File System Access API)
  try {
    const { saveToDirHandle } = await import('./backupLocation.js');
    if (await saveToDirHandle(filename, blob)) return;
  } catch { /* fall through */ }

  // Fall back to browser download
  const url = URL.createObjectURL(blob);
  const a   = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Import ─────────────────────────────────────────────────────────────────

// Extracts the character object embedded in a PDF generated by this app.
// Searches the raw PDF bytes for the MAGE_DATA marker written into the
// document keywords when the PDF was created.
export async function importFromPDF(file) {
  const buffer = await file.arrayBuffer();
  return extractFromPDFBytes(new Uint8Array(buffer));
}

function extractFromPDFBytes(bytes) {
  // PDF info dictionary is uncompressed; decode as latin-1 to preserve every byte.
  let text = '';
  for (let i = 0; i < bytes.length; i++) {
    text += String.fromCharCode(bytes[i]);
  }
  const match = text.match(/MAGE_DATA:([A-Za-z0-9+/=]+)/);
  if (!match) {
    throw new Error(
      'No character data found in this PDF.\n' +
      'Only PDFs exported by the Mage Companion app can be re-imported.'
    );
  }
  const bin  = atob(match[1]);
  const u8   = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
  return JSON.parse(new TextDecoder().decode(u8));
}

// Extracts all characters from a backup ZIP that contains PDF files.
// Returns an array of character objects.
export async function importFromPDFZip(file) {
  const buffer  = await file.arrayBuffer();
  const entries = await new Promise((resolve, reject) => {
    unzip(new Uint8Array(buffer), (err, data) => (err ? reject(err) : resolve(data)));
  });

  const pdfKeys = Object.keys(entries).filter(k => k.toLowerCase().endsWith('.pdf'));
  if (!pdfKeys.length) throw new Error('No PDF files found inside this ZIP.');

  const results  = [];
  const failures = [];
  for (const key of pdfKeys) {
    try {
      results.push(extractFromPDFBytes(entries[key]));
    } catch {
      failures.push(key);
    }
  }
  if (!results.length) {
    throw new Error('None of the PDFs in this ZIP contained importable character data.');
  }
  return { chars: results, skipped: failures };
}
